#FROM ubuntu:latest
#LABEL authors="Dragana"

#ENTRYPOINT ["top", "-b"]
# docker/Dockerfile.handler
FROM python:3.9-slim

WORKDIR /app

COPY data_handler_service.py .

RUN pip install -r requirements.txt

CMD ["python", "data_handler_service.py"]